#!/bin/bash
# Quick Guide: Using Aider with Files Outside Home Directory

echo "=================================================="
echo "Working with Files in Different Directories"
echo "=================================================="
echo ""
echo "Method 1: Navigate to the project directory first"
echo "--------------------------------------------------"
echo ""
echo "cd /path/to/your/project"
echo "./path/to/scripts/start_aider.sh --whole"
echo ""
echo "Or if the script is in ~/LLM:"
echo "cd /path/to/your/project"
echo "~/LLM/scripts/start_aider.sh --whole"
echo ""
echo ""
echo "Method 2: Use absolute paths in Aider"
echo "--------------------------------------------------"
echo ""
echo "1. Start Aider from anywhere:"
echo "   ./scripts/start_aider.sh --whole"
echo ""
echo "2. Inside Aider, add files with absolute paths:"
echo "   /add /full/path/to/your/file.py"
echo "   /add /home/user/projects/myproject/main.py"
echo ""
echo ""
echo "Method 3: Start Aider with file arguments"
echo "--------------------------------------------------"
echo ""
echo "cd /path/to/your/project"
echo "~/LLM/scripts/start_aider.sh --whole file1.py file2.py"
echo ""
echo "Or with absolute paths:"
echo "~/LLM/scripts/start_aider.sh --whole /full/path/to/file.py"
echo ""
echo ""
echo "Method 4: Symlink your project (if needed often)"
echo "--------------------------------------------------"
echo ""
echo "# Create a symlink in your home directory"
echo "ln -s /path/to/your/project ~/myproject"
echo "cd ~/myproject"
echo "~/LLM/scripts/start_aider.sh --whole"
echo ""
echo ""
echo "Examples:"
echo "=================================================="
echo ""
echo "Example 1: Working on a project in /home/user/projects/webapp"
echo ""
echo "  cd /home/user/projects/webapp"
echo "  ~/LLM/scripts/start_aider.sh --whole"
echo ""
echo "  # Inside Aider:"
echo "  /add src/main.py"
echo "  /add src/utils.py"
echo ""
echo ""
echo "Example 2: Working on multiple projects"
echo ""
echo "  cd /home/user/projects/project1"
echo "  ~/LLM/scripts/start_aider.sh --whole src/*.py"
echo ""
echo ""
echo "Example 3: Using absolute paths"
echo ""
echo "  ~/LLM/scripts/start_aider.sh --whole"
echo ""
echo "  # Inside Aider:"
echo "  /add /home/user/documents/code/script.py"
echo "  /add /var/www/html/index.php"
echo ""
echo ""
echo "Tips:"
echo "=================================================="
echo ""
echo "• Aider works with any directory, just cd there first"
echo "• Use /add with absolute or relative paths inside Aider"
echo "• You can add files from multiple directories in one session"
echo "• Use /ls to see current working directory"
echo "• Use /drop to remove files from context"
echo ""
echo "Common Aider commands for file management:"
echo "  /add <file>      - Add a file (supports wildcards)"
echo "  /add *.py        - Add all Python files in current dir"
echo "  /drop <file>     - Remove a file from context"
echo "  /ls              - List files in context"
echo "  /clear           - Clear chat history"
echo ""
